import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Since RootLayout does not use hooks, no need for "use client";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
